ci:
  - changed-files:
      - any-glob-to-any-file: .github/**
      - any-glob-to-any-file: _tools/**
      - any-glob-to-any-file: deno.json
      - any-glob-to-any-file: tsconfig*.json

builder:
  - changed-files:
      - any-glob-to-any-file: builder/**

common:
  - changed-files:
      - any-glob-to-any-file: common/**

config:
  - changed-files:
      - any-glob-to-any-file: config/**

context:
  - changed-files:
      - any-glob-to-any-file: context/**

convert:
  - changed-files:
      - any-glob-to-any-file: convert/**

i18n:
  - changed-files:
      - any-glob-to-any-file: i18n/**

logging:
  - changed-files:
      - any-glob-to-any-file: logging/**

reactivity:
  - changed-files:
      - any-glob-to-any-file: reactivity/**

realcss:
  - changed-files:
      - any-glob-to-any-file: realcss/**

realdom:
  - changed-files:
      - any-glob-to-any-file: realdom/**

router:
  - changed-files:
      - any-glob-to-any-file: router/**

rpc:
  - changed-files:
      - any-glob-to-any-file: rpc/**

templater:
  - changed-files:
      - any-glob-to-any-file: templater/**
