map $uri $cacheable {
  ~\.js$         0;
  ~\.css$        0;
}
map $cacheable $cache_control {
  0       "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
  default "public, max-age=31536000";
}
map $cacheable $expire {
  0 off;
  1 1y;
}

$SERVERS
